import type { Metadata } from "next";
import {Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FontSizeProvider } from '@/components/FontSizeContext';

const kantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "cdcCalendar",
  description: "Generated by CDC",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<html lang="en">
    <FontSizeProvider>
      <body className={`flex flex-col min-h-screen ${kantumruy.variable} antialiased`}>
        <Navbar />
        
        {/* Middle content fills available space */}
          <div className="flex-1 mb-6">{children}</div>
          
          {/* Sticky footer */}
          <div className="sticky bottom-0">
            <Footer />
          </div>
      </body>
    </FontSizeProvider>
  </html>
  
  );
}
