import type { Metadata } from "next";
import {Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const kantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "cdcCalendar",
  description: "Generated by CDC",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<html lang="en">
    <body className={`flex flex-col min-h-screen ${kantumruy.variable} antialiased`}>
      <Navbar />
      
      {/* Middle content fills available space dynamically */}
      <div className="flex-1 mb-10">{children}</div>
      
      <Footer />
    </body>
  </html>
  
  );
}
